### ISSUE TITLE
Custom and Official Factions for Pilot Cards

### ISSUE THREAD

**Issue by Hinny** [Hinny/strange-eons-xwing2#9]
- [x] Front: Custom Example
- [x] Front: Empire Preset (don't draw line art over)
- [x] Front: Rebel Preset (don't draw line art over)
- [x] Front: Scum Preset (don't draw line art over)
- [x] Front: Paint faction symbol (portrait)
- [ ] Front: Paint optional faction secondary texture overlays (portrait).
- [x] Token: Draw dark grey text area
- [x] Token: Draw black Icon and Initiative areas
- [x] Token: Draw all divider lines in faction colors 1
- [x] Token: Draw gradient art
- [x] Token: Draw fire arcs based on faction color
- [x] Backside: Empire Preset (don't draw line art over)
- [x] Backside: Rebel Preset (don't draw line art over)
- [x] Backside: Scum Preset (don't draw line art over)
- [x] Backside: Paint Faction texture
- [x] Backside: Paint faction symbol
- [ ] Backside: Paint optional faction secondary texture overlays.
- [x] Backside: Optional Draw thin transparent dark line are over the faction texture
- [x] Backside: Optional Draw shadow gradient from the bottom (see rebel faction)
- [x] Backside: Optional Draw shadow radial gradient from the edges (see Imperial faction)
- [ ] Front and Backside: Optional "broken paint" alpha mask on faction symbol
- [ ] Front and Backside: Optional "broken paint" alpha mask on secondary texture overlays
- [x] rebel ship preset
- [x] empire ship preset
- [x] scum ship preset
- [x] update pilot card icon to 2nd ed
- [x] update plug in info (only pilot cards included, no german yet etc)

**Comment by Hinny** [comment]
Requires access to official pilot cards and ship tokens for scanning and inspiration etc.

**Comment by Hinny** [comment]
![image](https://user-images.githubusercontent.com/7380773/42138765-e1c8d1d0-7d82-11e8-9a92-99dedcd6e6b3.png)

**Comment by Hinny** [comment]
Use alpha value < 1 for gradient art, instead of completely new color.

**Comment by Hinny** [comment]
API Notes
Close
The API Notes section contains basic pointers to get you looking in the right direction. For more complete information, open a Document Browser window in Strange Eons.

Compiled plug-ins will generally load image resources exclusively through static methods in ResourceKit. Scripted plug-ins usually prefer to use the functions in the imageutils library, which provides added flexibility and convenience. In either case, loading an image resource is trivial: call ResourceKit.getImage or ImageUtils.get (respectively) with the image's resource path. If you need to load a number of images at one time, you can use ResourceKit.getImagesQuietly to load the images in parallel on systems with multiple CPUs or cores.

Image Manipulation
The class ca.cgjennings.graphics.ImageUtilities provides a number of low-level static helper methods for manipulating images. The package ca.cgjennings.graphics.filters provides several image filters that you can use to produce special effects when drawing game components, such as blurring, greyscale conversion, and glow effects. The package ca.cgjennings.graphics.composites contains a number of painting composites that produce effects similar to the layer blending modes found in bitmap editing applications.

**Comment by Hinny** [comment]
How to paint the upper and lower panels on the front:
1. Use clip stencil on portrait to give the user something to work with
1. Take the image and merge it with the alpha value of a predefined template, so that only areas that should be visible is visible.
1. Paint the combined image.

**Comment by Hinny** [comment]
Put images in different folders:
1. Example
1. Faction specific
1. Framework

**Comment by eroohen** [comment]
https://github.com/Hinny/strange-eons-xwing2/tree/custom_frames

**Comment by Hinny** [comment]
Use fillpolygon to define the clip stencil and alpha mask.
